// <auto-generated />
using System;
using CasaSim.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasaSim.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619193419_AddNewScraperSources")]
    partial class AddNewScraperSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CasaSim.Core.Data.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_agency");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_agency_slug");

                    b.ToTable("agency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Remax Pombal",
                            Slug = "remax-pombal",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WebsiteUrl = "https://www.remax.pt"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Century21 Pombal",
                            Slug = "century21-pombal",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WebsiteUrl = "https://www.century21.pt"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "ERA Pombal",
                            Slug = "era-pombal",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WebsiteUrl = "https://www.era.pt"
                        });
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<decimal?>("AreaM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("area_m2");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bathrooms");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bedrooms");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("canonical_url");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EnergyClass")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("energy_class");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<decimal?>("LandAreaM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("land_area_m2");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int?>("ParkingSpaces")
                        .HasColumnType("integer")
                        .HasColumnName("parking_spaces");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("price_type");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("property_type");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.HasKey("Id")
                        .HasName("pk_listing");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_listing_city");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_listing_location_id");

                    b.HasIndex("Price")
                        .HasDatabaseName("ix_listing_price");

                    b.HasIndex("PropertyType")
                        .HasDatabaseName("ix_listing_property_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_listing_status");

                    b.HasIndex("AgencyId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_listing_agency_id_external_id");

                    b.ToTable("listing", (string)null);
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ListingFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_listing_feature");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_feature_listing_id");

                    b.ToTable("listing_feature", (string)null);
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alt_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_listing_image");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_image_listing_id");

                    b.ToTable("listing_image", (string)null);
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address_line2");

                    b.Property<Point>("Coordinate")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("coordinate");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("district");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Geohash")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("geohash");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("municipality");

                    b.Property<string>("Parish")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parish");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("RawAddress")
                        .HasColumnType("text")
                        .HasColumnName("raw_address");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("Coordinate")
                        .HasDatabaseName("ix_location_coordinate");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordinate"), "GIST");

                    b.HasIndex("Municipality")
                        .HasDatabaseName("ix_location_municipality");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ScrapeListingChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("AgencySlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("agency_slug");

                    b.Property<string>("ChangeSummaryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("change_summary_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid>("ScrapeLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("scrape_log_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_scrape_listing_change");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_scrape_listing_change_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_scrape_listing_change_created_at");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_scrape_listing_change_listing_id");

                    b.HasIndex("ScrapeLogId")
                        .HasDatabaseName("ix_scrape_listing_change_scrape_log_id");

                    b.ToTable("scrape_listing_change", (string)null);
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ScrapeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text")
                        .HasColumnName("error_details");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("ListingsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("listings_created");

                    b.Property<int>("ListingsFound")
                        .HasColumnType("integer")
                        .HasColumnName("listings_found");

                    b.Property<int>("ListingsRemoved")
                        .HasColumnType("integer")
                        .HasColumnName("listings_removed");

                    b.Property<int>("ListingsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("listings_updated");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scrape_log");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_scrape_log_agency_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_scrape_log_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_scrape_log_status");

                    b.ToTable("scrape_log", (string)null);
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ScraperSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("AgencySlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("agency_slug");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval")
                        .HasColumnName("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ScraperKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scraper_key");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("TargetDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("target_description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scraper_source");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_scraper_source_agency_id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_scraper_source_enabled");

                    b.HasIndex("ScraperKey")
                        .IsUnique()
                        .HasDatabaseName("ix_scraper_source_scraper_key");

                    b.ToTable("scraper_source", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            AgencyId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            AgencySlug = "remax-pombal",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 0, 1, 0, 0),
                            Name = "Remax Pombal",
                            ScraperKey = "Remax",
                            SourceUrl = "https://www.remax.pt",
                            TargetDescription = "Remax listings for Pombal",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            AgencyId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            AgencySlug = "century21-pombal",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 0, 1, 0, 0),
                            Name = "Century21 Pombal",
                            ScraperKey = "Century21",
                            SourceUrl = "https://www.century21.pt",
                            TargetDescription = "Century21 sale and rent listings for Pombal",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            AgencyId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            AgencySlug = "era-pombal",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 0, 1, 0, 0),
                            Name = "ERA Pombal",
                            ScraperKey = "ERA",
                            SourceUrl = "https://www.era.pt/imoveis/agencia/pombal",
                            TargetDescription = "ERA agency listings for Pombal",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000004"),
                            AgencySlug = "valorfin-imoveis",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "Valorfin Imóveis",
                            ScraperKey = "Valorfin Imóveis",
                            SourceUrl = "https://valorfinimoveis.pt",
                            TargetDescription = "CRM360 platform — Valorfin Imóveis",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000005"),
                            AgencySlug = "argilipe",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "Argilipe",
                            ScraperKey = "Argilipe",
                            SourceUrl = "https://www.argilipe.pt",
                            TargetDescription = "CRM360 platform — Argilipe Imobiliária",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000006"),
                            AgencySlug = "imopombal",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "ImoPombal",
                            ScraperKey = "ImoPombal",
                            SourceUrl = "https://www.imopombal.pt",
                            TargetDescription = "eGO platform — ImoPombal",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000007"),
                            AgencySlug = "lionscastles",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "LionsCastles",
                            ScraperKey = "LionsCastles",
                            SourceUrl = "https://www.lionscastles.pt",
                            TargetDescription = "eGO platform — LionsCastles",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000008"),
                            AgencySlug = "habifit",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "Habifit",
                            ScraperKey = "Habifit",
                            SourceUrl = "https://www.habifit.pt",
                            TargetDescription = "eGO platform — Habifit",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000009"),
                            AgencySlug = "cosy-imobiliaria",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "Cosy Imobiliária",
                            ScraperKey = "Cosy Imobiliária",
                            SourceUrl = "https://www.cosyimobiliaria.pt",
                            TargetDescription = "eGO platform — Cosy Imobiliária",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000010"),
                            AgencySlug = "moderno-imoveis",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "Moderno Imóveis",
                            ScraperKey = "Moderno Imóveis",
                            SourceUrl = "https://www.modernoimoveis.pt",
                            TargetDescription = "WordPress — Moderno Imóveis",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000011"),
                            AgencySlug = "neves-terlouw",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "Neves & Terlouw",
                            ScraperKey = "Neves & Terlouw",
                            SourceUrl = "https://www.nevesterlouw.com",
                            TargetDescription = "Custom site — Neves & Terlouw",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000012"),
                            AgencySlug = "veigas",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "Veigas",
                            ScraperKey = "Veigas",
                            SourceUrl = "https://www.veigas.eu",
                            TargetDescription = "Next.js — Veigas Imobiliária",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000013"),
                            AgencySlug = "zome",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "Zome",
                            ScraperKey = "Zome",
                            SourceUrl = "https://www.zome.pt/pt/leiria-h40157/imoveis",
                            TargetDescription = "Nuxt/Vue — Zome Leiria district",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.Listing", b =>
                {
                    b.HasOne("CasaSim.Core.Data.Entities.Agency", "Agency")
                        .WithMany("Listings")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listing_agency_agency_id");

                    b.HasOne("CasaSim.Core.Data.Entities.Location", "Location")
                        .WithMany("Listings")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_listing_locations_location_id");

                    b.Navigation("Agency");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ListingFeature", b =>
                {
                    b.HasOne("CasaSim.Core.Data.Entities.Listing", "Listing")
                        .WithMany("Features")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_feature_listing_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ListingImage", b =>
                {
                    b.HasOne("CasaSim.Core.Data.Entities.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_image_listing_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ScrapeListingChange", b =>
                {
                    b.HasOne("CasaSim.Core.Data.Entities.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_scrape_listing_change_listing_listing_id");

                    b.HasOne("CasaSim.Core.Data.Entities.ScrapeLog", "ScrapeLog")
                        .WithMany("ListingChanges")
                        .HasForeignKey("ScrapeLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scrape_listing_change_scrape_log_scrape_log_id");

                    b.Navigation("Listing");

                    b.Navigation("ScrapeLog");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ScrapeLog", b =>
                {
                    b.HasOne("CasaSim.Core.Data.Entities.Agency", "Agency")
                        .WithMany("ScrapeLogs")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_scrape_log_agency_agency_id");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ScraperSource", b =>
                {
                    b.HasOne("CasaSim.Core.Data.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_scraper_source_agency_agency_id");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.Agency", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("ScrapeLogs");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.Listing", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.Location", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("CasaSim.Core.Data.Entities.ScrapeLog", b =>
                {
                    b.Navigation("ListingChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
